
(declaim (optimize (debug 3)))

(in-package :arc/test)

(deftest t-equal/cps 
  (chk (%equal/cps '(a b) '(a b)))
  (chk (%equal/cps '(#\a 1) '(#\a 1)))
  (chk (%equal/cps '(#:k) '(#:z)))
  (chk (not (%equal/cps '(#:i #:i) '(#:a #:b))))
  (chk (not (%equal/cps '(#:i #:j) '(#:a #:a))))
  (chk (%equal/cps '(fn (#:k1) a b c) '(fn (#:k2) a b c)))
  (chk (%equal/cps '(#:k2 #:k3 1 #\a "b") '(#:a2 #:a3 1 #\a "b")))
  (chk (not (%equal/cps '(#:k2 #:k3 1 #\a "b") '(#:a3 #:a3 1 #\a "b")))))

(deftest c-simple
  (chkcps 'a "a")
  (chkcps #\a "#\\a")
  (chkcps "hi" "\"hi\"")
  (chkcps '(+ 1 x) "(+ 1 x)")
  (chkcps '(sqrt (+ 1 x)) "(sqrt (+ 1 x))"))

(deftest c-block
  (chkcps '(fn (#:k) (#:k a))     "(fn () a)")
  (chkcps '(fn (#:k) a (#:k b))   "(fn () a b)")
  (chkcps '(fn (#:k) a b (#:k c)) "(fn () a b c)")
  (chkcps '(fn (#:k x) (#:k (+ 1 (sqrt x))))
	  "(fn (x) (+ 1 (sqrt x)))")
  (chkcps '(fn (#:k) (a (fn (#:r) (#:k b)) 1))
	  "(fn () (a 1) b)")
  (chkcps '(fn (#:k) a (b (fn (#:r) (#:k c)) 1))
	  "(fn () a (b 1) c)")
  (chkcps '(fn (#:k) a (b (fn (#:r) c (#:k d)) 1))
	  "(fn () a (b 1) c d)")
  (chkcps '(fn (#:k) (a (fn (#:r) (#:k #:r)) 1))
	  "(fn () (a 1))")
  (chkcps '(fn (#:k) (a (fn (#:r1) (b (fn (#:r2) (#:k #:r2)) 2)) 1))
	  "(fn () (a 1) (b 2))"))

(deftest c-if
  (chkcps '(if (< x 0) 0 1) "(if (< x 0) 0 1)")
  (chkcps '(a (fn (#:r1) (if #:r1 x y)) 1)
	  "(if (a 1) x y)")
  (chkcps '(a (fn (#:r1) (+ 1 (if #:r1 x y))) 1)
	  "(+ 1 (if (a 1) x y))")
  (chkcps '(a (fn (#:r1) (b (fn (#:r2) (if #:r1 x #:r2 y z)) 2)) 1)
	  "(if (a 1) x (b 2) y z)")
  (chkcps '(if (< x 0) 
	       (hi (fn (#:r1) #:r1) 5) 
	       x)
	  "(if (< x 0) (hi 5) x)")
  (chkcps '(if x 0 y 1 (a (fn (#:k) (if #:k 2 3)) 0))
	  "(if x 0 y 1 (a 0) 2 3)")
  (chkcps '(if x 0 (a (fn (#:k) (if #:k 2 y 3 4)) 1))
	  "(if x 0 (a 1) 2 y 3 4)"))

(deftest c-funcall
  (chkcps '(a (fn (#:k) :k) (+ 1))
	  "(a (+ 1))")
  (chkcps '(b (fn (#:k1)
		(a (fn (#:k2) #:k2)
		   (+ 1)
		   #:k1))
	    2)
	  "(a (+ 1) (b 2))")
  (chkcps '(hi (fn (#:k)
		(+ 1 (- 2 #:k)))
	    (sqrt x))
	  "(+ 1 (- 2 (hi (sqrt x))))")
  (chkcps '(fn (#:k x f) (f (fn (#:r1) (#:k #:r1)) (+ 1 x)))
	  "(fn (x f) (f (+ 1 x)))")
  (chkcps '(b (fn (#:r1) (a (fn (#:r2) #:r2) #:r1)) x)
	  "(a (b x))")
  (chkcps '(a (fn (#:r1) (+ #:r1 2)) x)
	  "(+ (a x) 2)")
  (chkcps '(a (fn (#:r1)
		(b (fn (#:r2) 
		     (+ #:r1 #:r2))
		 x))
	    1)
	  "(+ (a 1) (b x))")
  (chkcps '(b (fn (#:k1) 
		(a (fn (#:k2) 
		     (* #:k2 2)) 
		   (+ #:k1 1))) 
	    1)
	  "(* (a (+ (b 1) 1)) 2)"))
